### ISSUE TITLE
FlooPowder doesn't work anymore after cancelling teleport (1.7.10)

### ISSUE THREAD

**Issue by kutschkem** [fredtargaryen/Floocraft#1]
(I think) After cancelling the teleport, the floo powder doesn't work at that fireplace anymore. It seems to be related to the position, I think, because when I extinguish the fire and/or replace the flammable block, it doesn't start working again. Building a new fireplace somewhere else makes it work one time, but then produces the same behavior after cancelling.

I see that you have some fixes that sound like they could be related in the master branch, any chance to backport it to the 1.7.10 branch?

**Comment by fredtargaryen** [comment]
Thanks for posting this; I still don't know much about GitHub so it's going to take some time for me to separate the different versions before I can investigate. Unless you know how to do it?

**Comment by kutschkem** [comment]
First, can you try that cancelling works as expected in 1.8? I will try and build your stuff, and then see if I can get your last two commits on the 1.7.10 branch you have. I don't know if that will change anything, but at least it's a start.

**Comment by fredtargaryen** [comment]
I've grabbed all the current code and stuck it in a new 1.8 repo, so I think now it's just a case of reverting to the last 1.7.10 commit. Although I tried that and it told me there were unmerged files, so I dealt with that, retried and it again failed to revert, but without giving a reason. If it doesn't work for you, I'll just manually change the code back.

**Comment by kutschkem** [comment]
You can just work with branches, you even have a 1.7.10 branch already. Here is what I would do:

git checkout Floocraft-1.7.10
git rebase --onto Floocraft-1.7.10 master~2 master

which gives a bunch of conflicts which I didn't take the time to resolve.

**Comment by fredtargaryen** [comment]
I read that branches are meant to be short term so I'm a little bit doubtful about this but I'll try having a branch for each version. Going back to your bug, just to make sure I'm not missing something very obvious, how long have you been waiting to go back into the fire? There's a delay of a few seconds after cancelling, to give you time to get out of the fire before the menu pops up again and stops you leaving.

**Comment by kutschkem** [comment]
How long is the cooldown? I am certain this problem persisted for several minutes at least, through restarts. I just tried again and teleportation triggered the same problem. Interestingly I didn't change the fireplace before, so it seems that it was correctly detected. Maybe the cooldown is buggy? Here is what I just did:
1. teleport from named fireplace 1 to named fireplace 2
2. straight away (after fire is red again, obviously), try to teleport to fireplace 2 from 1. Doesn't work, fireplace 2 is printed red, so I cancel.
3. Now both fireplaces won't accept floo powder.

And this problem persists for a long time (exactly how long I am not sure, but since I just succesfully teleported, the problem seems to go away after several hours). At least 15-30 minutes, I'd say. At most 24 hours playing time.

**Comment by fredtargaryen** [comment]
I've tried this just now, and had no problems. I certainly haven't coded in anything to do with waiting any more than the GUI cooldown time, which is 126 client ticks...
What are the coordinates of your fireplaces? I habitually build test fireplaces very close together. Maybe fireplace 2 is in a chunk which was not loaded when you teleport?
Do you have any other mods or plugins installed, that you know modify chunk, block or entity behaviour?

I forgot to mention that the 1.8 GUI doesn't work so I can't test teleporting there.
Edit: the 1.8 GUI works now, and I'm not having any problems teleporting.
