### ISSUE TITLE
[1.10] Set on fire when teleporting

### ISSUE THREAD

**Issue by DNRyan** [fredtargaryen/Floocraft#10]
MC: 1.10.2
Forge: 12.18.3.2185
Mod: Floocraft-1.7.6
Immediately after teleporting, I am set on fire because the fire in the fireplace is normal.
Doesn't seem like the fireplace being teleported to is turned into a floocraft fire
Hope that makes sense

**Comment by fredtargaryen** [comment]
Hi. I'm just finishing up an update for 1.12; I will port back to 1.11.2 and 1.10.2 after that. The code looks OK to me so maybe I just forgot to upload a new version.

**Comment by DNRyan** [comment]
That would be great, thank you. Love your mod!

**Comment by fredtargaryen** [comment]
I didn't manage to find the bug you described when testing today. In a moment I'll link you a beta of 1.10.2-1.8; please could you try it and see if the problem is still there?
Edit: https://minecraft.curseforge.com/projects/floocraft/files/2475224

Cheers!

**Comment by DNRyan** [comment]
Will try out the beta soon and let you know. 
Also, I do have other mods installed alongside floocraft so will do a clean install with only floocraft installed to ensure the problem is not my end.

Thanks

**Comment by DNRyan** [comment]
Have just tested the beta and the bug has gone! Didn't end up trying out a clean install because the beta has fixed the problem.
Thank you

**Comment by fredtargaryen** [comment]
Brilliant! Thanks very much. Glad you enjoy the mod.
