### ISSUE TITLE
Floower Pot doesn't keep Floo Powder

### ISSUE THREAD

**Issue by blockspiders** [fredtargaryen/Floocraft#12]
When I place powder in the Floower Pot, it all disappears the next time I open the pot's inventory. This pot is close to an existing, active green fire that's connected to the network and hasn't run out of charges. It happened to both 8tp and 1tp concentrations.

**Comment by fredtargaryen** [comment]
I'm glad you mentioned this just before I was going to upload a new version. Fixed in 1.9.0; I'm sorry for your lost powder.

**Comment by blockspiders** [comment]
This happened to me in a 1.12.2 server. Is there a fix planned for that version as well?

**Comment by fredtargaryen** [comment]
I've just copied it in. The commit and download will be available a bit later today. Thank you for the heads up!
