### ISSUE TITLE
GUI Clipping/Overlap

### ISSUE THREAD

**Issue by dragonshardz** [fredtargaryen/Floocraft#13]
Depend on one;s GUI scale and resolution, once you get beyond the number of floo signs that can fit between the top of the GUI window and the GO button, users will get teleported to locations hidden "behind" the GO button.

This is with the latest version on 1.12.2. Recommend locking GUI buttons to bottom bar of GUI.

**Comment by fredtargaryen** [comment]
Oh, that was daft of me. I'll check all the GUIs at every scale and fix them accordingly. Thanks!
