### ISSUE TITLE
Request - x2 Close fixed and/or invalid issues (OCD) - Add interdimensional teleportation.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [fredtargaryen/Floocraft#14]
I am having a really hard time finding good ways to teleport between dimensions. Although FTBUtilities works with /warp < LOCATION > it is not practical for none admins. I got floocraft and fell in love with it the first test. It was clean and felt balanced. Unfortunately it failed to do the one thing I wanted it to do most - trans-dimensional teleportation. So I guess now I will continue my struggle.

**Comment by fredtargaryen** [comment]
Hi, and thanks for playing the mod!

I have deliberately not let the player teleport between dimensions. I thought this would balance how fast the teleportation is. Also I thought there might be dimensions that the player isn't supposed to be able to just leave, and I wouldn't want Floocraft to become a mod that's just used to make other mods easier.

If there was more support for it, or the issue I mentioned is not as big a deal as I thought it would be, I might reconsider it.

I will review the issue list before I port Floocraft to 1.13.2.

**Comment by P3rf3ctXZer0** [comment]
Alright thank you.
