### ISSUE TITLE
Mo Creatures Conflict

### ISSUE THREAD

**Issue by EightBlade** [fredtargaryen/Floocraft#18]
https://paste.dimdev.org/hegajinene.mccrash

Details above.

**Comment by fredtargaryen** [comment]
Hi, thanks for reporting this. I'm quite confident this has been fixed in the alpha versions beyond 1.9.3. If you don't want to upgrade to those I will be trying to create a final 1.12.2 release soon.

**Comment by fredtargaryen** [comment]
Closing because I believe this is fixed as of [version 1.12.2-1.9.5](https://minecraft.curseforge.com/projects/floocraft/files/2720134). Please reopen if this isn't the case.
