### ISSUE TITLE
Server Crash - Floocraft 1.14.4-1.9.6-beta.1

### ISSUE THREAD

**Issue by DvlDddy** [fredtargaryen/Floocraft#23]
Running latest recommended server release 1.14.4 - 28.1.0

Error as follows:

[10:47:57] [Server thread/FATAL] [ne.mi.fm.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod File Floocraft+1.14.4-1.9.6.jar needs language provider javafml:28 to load
?7We have found 28.1

**Comment by Knito58** [comment]
Same problem here.
MC 1.14.4, Forge 28.1.1, Floocraft 1.9.6

**Comment by ghost** [comment]
same

**Comment by ghost** [comment]
28.1.10

**Comment by fredtargaryen** [comment]
Thank you for reporting; this will be fixed in the next version.
