### ISSUE TITLE
1.14.4 Floower pot activates illegal places

### ISSUE THREAD

**Issue by Knito58** [fredtargaryen/Floocraft#25]
In my blaze farm there's a floo fire place with a floower pot on it. From time to time it activates a place which does not qualify as fire place at all: A piece of cobble with no valid brick building around it. It uses a floo powder each time and I can walk into and select valid places as target.

![2019-09-29_18 54 23](https://user-images.githubusercontent.com/2604989/65835823-2fe15800-e2eb-11e9-8da2-05e954656d09.png)

Forge 28.1.26, MC 1.14.4, Floocraft 1.9.7

**Comment by Knito58** [comment]
The first fire was one block to the right adjacent to the gobber glass. I extinguished it with my sword. After two minutes the floo fire respawned at the location shown in the picture. Each time one floo powder was consumed from the floower pot.

**Comment by fredtargaryen** [comment]
Does that area have a ceiling? The fireplace detection could be interpreting your entire wall as the back of a massive fireplace. And fireplaces can be made of any solid block, not just brick. Also are these green flames appearing from fire blocks or out of thin air?

**Comment by Knito58** [comment]
Yep it has a ceiling. 
![2019-09-29_19 52 18](https://user-images.githubusercontent.com/2604989/65836874-ca916500-e2f2-11e9-8813-4ab81eb46286.png)
The floor is cobble, the ceiling is netherrack and sometimes quartz. A blaze lit a fire and the floower pot made it to floo fire again. I think I should extinguish the orginal fire place as long as I harvest blazes as it depleates my floo powder rapidly.

**Comment by Knito58** [comment]
Ok should take rather the floo powder from the pot...

**Comment by fredtargaryen** [comment]
That is working as intended then. You could simply reposition the Floower Pot somewhere out of the way. It works in a 11x11x11 grid centred around the fireplace.

**Comment by fredtargaryen** [comment]
[Actually, a customisable radius might not be such a bad thing...](https://github.com/fredtargaryen/Floocraft/issues/26)

**Comment by Knito58** [comment]
I agree. Would be nice if it was "per pot" and not one fits all :)

**Comment by fredtargaryen** [comment]
Agreed, I'll clarify that in the issue text.

**Comment by fredtargaryen** [comment]
Closed because working as intended but a customisable radius will be made later. Thank you!

**Comment by Knito58** [comment]
Thank you. The customisable radius will fix my issue. Until then, I'll take the powder from the pot when near fire.
Great transportation mod!
