### ISSUE TITLE
Failed to load (private server

### ISSUE THREAD

**Issue by Eiizen** [fredtargaryen/Floocraft#30]
Hi,

Thanks for this mod ! 
I know it's a beta for now (1.15.2), but have you any idea ? (forge private server)
(OK in solo mode)

Thank you !  

[crash-2020-04-06_18.38.30-server.txt](https://github.com/fredtargaryen/Floocraft/files/4439707/crash-2020-04-06_18.38.30-server.txt)
[latest.log](https://github.com/fredtargaryen/Floocraft/files/4439738/latest.log)

**Comment by fredtargaryen** [comment]
Hi, thanks for flagging this up! I'm sorry this happened; I must have forgotten to test the server :/

This should be fixed as of https://github.com/fredtargaryen/Floocraft/commit/df35508c653b77e0b592692e31c64a0537b9c060.

**Comment by fredtargaryen** [comment]
Hi again, the latest release should have resolved your problem.

**Comment by Eiizen** [comment]
Hi !

Thank you for your reply and your help.
It works perfectly.
Thank you for this mod which is super fun and is one of the least cheated
to use !

Le lun. 13 avr. 2020 à 17:40, James Curran <notifications@github.com> a
écrit :

**Comment by fredtargaryen** [comment]
Haha, you're very welcome!
