### ISSUE TITLE
cannot recover red sign

### ISSUE THREAD

**Issue by ftcsubs** [fredtargaryen/Floocraft#34]
is there a location in file to see x,y,z coords

**Comment by fredtargaryen** [comment]
Hi, sorry for the extremely late reply.

You can use [NBTExplorer](https://github.com/jaquadro/NBTExplorer/releases) to dig around in your world and change things; the fireplace coordinates will be in the `floocraftft` tag.

As of Floocraft 1.16.3-1.13.0-beta.1, the `/viewfireplace` command can be used to display fireplace names and coordinates in any dimension.
