### ISSUE TITLE
Placing Floo Sign Leads to Crash 1.16.3 beta

### ISSUE THREAD

**Issue by eanewsom** [fredtargaryen/Floocraft#35]
Placing the floo sign down causes Minecraft to crash in 1.16.3 beta version.

**Comment by fredtargaryen** [comment]
Hi! Sorry to hear that; do you have any other information? Like the crash log, or where you placed the block?

**Comment by fredtargaryen** [comment]
Never mind; I'm getting the same thing now. Very strange. Sorry, but it may take a while to fix.

**Comment by fredtargaryen** [comment]
[OK, looks like it's fixed](https://www.curseforge.com/minecraft/mc-mods/floocraft/files/3111592).

**Comment by fredtargaryen** [comment]
Closing as 7 days have passed with no mention that the bug is still present.
