### ISSUE TITLE
Broken loot tables

### ISSUE THREAD

**Issue by WenXin20** [fredtargaryen/Floocraft#37]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Floocraft v1.15.0`

Right-clicking the fire with any floo powder would not change the fire. In survival, it consumes the powder, but nothing changes.

All blocks also are missing loot tables, nothing drops when mined.

Also, the Floower Pot's gui also does not get darker when opened the way other gui's do.

![2020-12-21_12 23 15](https://user-images.githubusercontent.com/12000593/102809705-1614b080-4388-11eb-99b2-82a6828780db.png)

**Comment by fredtargaryen** [comment]
Hi!
Make sure you remember the backing wall for the fireplace.
I made a very silly mistake when adding the loot tables; sorry, I will get on that.
I'll fix the third issue too.

**Comment by WenXin20** [comment]
Ah, ok, I hadn't thought of that. Could you add that to the mod page? I didn't see an example of how it should look.

Also, could you prevent it from consuming floor powder if the fireplace frame is invalid?

**Comment by fredtargaryen** [comment]
Do you mean the CurseForge page? You can see the fireplace design in the preview video on that page, as well as the mod's banner image and a few different pages on the wiki. I would add the banner to the mod description page but need to speak to CurseForge to see how I can make changes to the page and be sure it won't damage the rest of the page's formatting...

I'll think about the floo powder consumption situation but right now would rather keep it how it is. Using a Floower Pot won't consume Powder if the fireplace is invalid though.

**Comment by WenXin20** [comment]
Ok, thanks

**Comment by fredtargaryen** [comment]
These should be fixed as of the above commits and Floocraft versions 1.15.2-1.14.2 and 1.16.3-1.15.1. Please could you confirm that on your side?

**Comment by WenXin20** [comment]
Alright, I'll see if I can give it a try soon.

**Comment by WenXin20** [comment]
Yep, both issues are fixed. :)

**Comment by fredtargaryen** [comment]
Great, thank you for reporting and confirming! I'll put up your suggestions as new issues and give them some thought.
