### ISSUE TITLE
Creative Floo Powder only lasts one teleport

### ISSUE THREAD

**Issue by WenXin20** [fredtargaryen/Floocraft#38]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Floocraft v1.15.0`

I used the creative floo powder on both fireplaces, but when teleporting, it turns back into normal fire after only one teleport.

Also, when the 'peek' button is pressed, the head that is displayed doesn't show the hat layer of the player's skin.

**Comment by fredtargaryen** [comment]
The creative Floo fire I teleport *from* doesn't change back, but the one I teleport *to* does. Is this what's happening for you?

**Comment by WenXin20** [comment]
Yes, that is what's happening to me too.

**Comment by fredtargaryen** [comment]
That should be fixed as of commit fc982446f753fa4387c9fb44351545097f023717 and Floocraft version 1.16.3-1.15.2. Please could you confirm that on your side?
