### ISSUE TITLE
[Crash] Exception while ticking a block

### ISSUE THREAD

**Issue by MysticAura** [fredtargaryen/Floocraft#4]
MC Version: 1.10.2
Forge Version: 2010
Mod Version: 1.7.5

Game crashes entirely. I was able to trigger this a couple of ways.
- Normally set up fire, break the brick behind the green flame (full floopot beside)
- The other seemed to happen when there was more than one fire lit (after the full floopot was placed) When it would try and light the 2nd flame..instant crash

[Crash Log](http://pastebin.com/FVurdG12)

**Comment by fredtargaryen** [comment]
Thank you! This will be patched next version.
