### ISSUE TITLE
Teleporting corrupts chunk of map

### ISSUE THREAD

**Issue by StokedTheorem** [fredtargaryen/Floocraft#41]
Recently teleported to an area of the map, and it crashed. When other players came near that chunk of the map, it would crash for them as well.

**Comment by fredtargaryen** [comment]
Wow. Sorry to hear that. Are you able to obtain a crash log? That would really help me debug this.

**Comment by StokedTheorem** [comment]
[crash-2021-02-01_18.53.22-client.txt](https://github.com/fredtargaryen/Floocraft/files/5907912/crash-2021-02-01_18.53.22-client.txt)
Sorry for the delay. We haven't had the issue for a while, but it happened again today.

**Comment by fredtargaryen** [comment]
Hi!
[Here's a potential fix](https://www.curseforge.com/minecraft/mc-mods/floocraft/files/3252775); I hope it works out for you. I'll leave this open for a month or so in case you're still having issues.

**Comment by fredtargaryen** [comment]
Hi, closing this one due to inactivity. I hope everything's going fine now; if not feel free to reopen.
