### ISSUE TITLE
Language files causing unintended text appearing

### ISSUE THREAD

**Issue by addstar** [fredtargaryen/Floocraft#44]
Hello,

I've noticed an issue since using Floocraft, where the word "MENUS" keeps appearing in random places in GUIs of other mods. I did some digging and noticed the file [en_us.json](https://github.com/fredtargaryen/Floocraft/blob/master/src/main/resources/assets/floocraftft/lang/en_us.json#L32) (and probably the other language files) has this line:
```
    "": "MENUS",
```
This is causes the word `MENUS` to appear anywhere an empty text is being used (since Floocraft is overriding empty text).

The simple fix would be to remove these entries (as well `BLOCKS`, `ITEMS` and `SUBTITLES`). I'd be happy to raise a PR if that would help.

**Comment by fredtargaryen** [comment]
Oops!! I thought that was a way of doing comments in lang files. I'll remove those soon

**Comment by addstar** [comment]
Wow, thanks for the super fast response and fix!! :clap: 

Just tested it and it fixed the issues I was seeing :grin:

**Comment by fredtargaryen** [comment]
Good stuff. Thank you for reporting!
