### ISSUE TITLE
1.12 Fatal error unable to join the server

### ISSUE THREAD

**Issue by Karnatour** [fredtargaryen/Floocraft#48]
Hi when using latest version of 1.12 floocraft if player puts 'ú' in name it will cause fatal error and player is stuck is it possible to add UTF-8 support ? I didnt test newer game version maybe the problem is fixed in them. Thanks error msg:
`Caused by: java.lang.IndexOutOfBoundsException: readerIndex(70) + length(1700995072) exceeds writerIndex(92): UnpooledSlicedByteBuf(ridx: 70, widx: 92, cap: 92/92, unwrapped: PooledUnsafeDirectByteBuf(ridx: 0, widx: 93, cap: 93))`

**Comment by fredtargaryen** [comment]
Hi, sorry for the supremely late reply. My policy was only to maintain the latest two Forge versions, even before I ended up doing no modding for several years, so I apologise but I won't be fixing this one. Thanks for reporting anyway; I'll look out for it when I find time to make mods again
